name: CD Kubernotes

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        pwd
        ls
        cd ./src/
        npm -v
        yarn -v
        yarn
        yarn docs:build
        cd ./docs/.vuepress/dist
        git init
        git add -A
        git commit -m 'deploy'
        git push -f git@github.com:kubernotes/kubernotes.github.io.git master:gh_update
      env:
        CI: true
